# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-14 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_foodtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtypes',
            name='childtypenames',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodtypes',
            name='typename',
            field=models.CharField(max_length=100),
        ),
    ]
